import type { Plan } from '@/types';

export const mockPlans: Omit<Plan, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    vendorId: 'v1',
    vendorName: '台北晶華酒店',
    title: '2025 晶華豪華年菜組',
    description: '主廚精心設計的經典年菜組合，適合全家團圓享用',
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',
    priceOriginal: 12800,
    priceDiscount: 9980,
    shippingFee: 0,
    shippingType: 'delivery',
    storageType: 'frozen',
    region: 'nationwide',
    city: '台北市',
    address: '台北市中山區中山北路二段39巷3號',
    servingsMin: 6,
    servingsMax: 8,
    orderDeadline: '2025-01-20',
    fulfillStart: '2025-01-25',
    fulfillEnd: '2025-01-28',
    canSelectDate: true,
    tags: ['粵式', '海鮮', '佛跳牆'],
    dishes: [
      '港式佛跳牆',
      '蒜蓉蒸龍蝦',
      '紅燒獅子頭',
      '櫻花蝦米糕',
      '清蒸石斑魚',
      '干貝海鮮羹',
    ],
    status: 'published',
  },
  {
    vendorId: 'v2',
    vendorName: '饗食天堂',
    title: '經典團圓宴 6-8人份',
    description: '嚴選台灣在地食材，傳統手藝製作',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
    priceOriginal: 6880,
    priceDiscount: 5880,
    shippingFee: 150,
    shippingType: 'both',
    storageType: 'frozen',
    region: 'north',
    city: '新北市',
    address: '新北市板橋區縣民大道二段7號',
    servingsMin: 6,
    servingsMax: 8,
    orderDeadline: '2025-01-22',
    fulfillStart: '2025-01-26',
    fulfillEnd: '2025-01-29',
    canSelectDate: true,
    tags: ['台式', '佛跳牆', '烏魚子'],
    dishes: [
      '台式佛跳牆',
      '烏魚子拼盤',
      '紅蟳米糕',
      '東坡肉',
      '白菜滷',
      '什錦海鮮羹',
    ],
    status: 'published',
  },
  {
    vendorId: 'v3',
    vendorName: '欣葉台菜',
    title: '古早味年菜禮盒',
    description: '傳承三代的道地台菜風味',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    priceDiscount: 4280,
    shippingFee: 200,
    shippingType: 'delivery',
    storageType: 'chilled',
    region: 'north',
    city: '台北市',
    address: '台北市中山區雙城街34之1號',
    servingsMin: 4,
    servingsMax: 6,
    orderDeadline: '2025-01-18',
    fulfillStart: '2025-01-27',
    fulfillEnd: '2025-01-28',
    canSelectDate: false,
    tags: ['台式', '素食'],
    dishes: [
      '紅燒蹄膀',
      '筍絲封肉',
      '長年菜',
      '芋頭糕',
    ],
    status: 'published',
  },
  {
    vendorId: 'v4',
    vendorName: '鼎泰豐',
    title: '精緻年節禮盒',
    description: '招牌小籠包搭配經典年菜',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop',
    priceOriginal: 3680,
    priceDiscount: 3280,
    shippingFee: 0,
    shippingType: 'pickup',
    storageType: 'chilled',
    region: 'north',
    city: '台北市',
    address: '台北市大安區信義路二段194號',
    servingsMin: 2,
    servingsMax: 4,
    orderDeadline: '2025-01-25',
    fulfillStart: '2025-01-28',
    fulfillEnd: '2025-01-29',
    canSelectDate: true,
    tags: ['粵式', '海鮮'],
    dishes: [
      '蟹粉小籠包',
      '紅燒牛肉麵',
      '蝦仁燒賣',
      '排骨蛋炒飯',
    ],
    status: 'published',
  },
  {
    vendorId: 'v5',
    vendorName: '長榮桂冠酒店',
    title: '御廚年菜套餐 10人份',
    description: '五星飯店主廚監製，頂級食材呈現',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    priceOriginal: 18800,
    priceDiscount: 15800,
    shippingFee: 0,
    shippingType: 'delivery',
    storageType: 'frozen',
    region: 'central',
    city: '台中市',
    address: '台中市西屯區台灣大道二段666號',
    servingsMin: 10,
    servingsMax: 12,
    orderDeadline: '2025-01-15',
    fulfillStart: '2025-01-24',
    fulfillEnd: '2025-01-27',
    canSelectDate: true,
    tags: ['粵式', '海鮮', '佛跳牆', '含酒'],
    dishes: [
      '鮑魚佛跳牆',
      '清蒸帝王蟹',
      '烏魚子米粉',
      'XO醬干貝',
      '紹興醉雞',
      '蔥爆牛柳',
      '白灼時蔬',
      '八寶芋泥',
    ],
    status: 'published',
  },
  {
    vendorId: 'v6',
    vendorName: '寬心園',
    title: '素食年菜禮盒',
    description: '健康蔬食，美味不減',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    priceDiscount: 3580,
    shippingFee: 100,
    shippingType: 'delivery',
    storageType: 'frozen',
    region: 'nationwide',
    city: '台北市',
    address: '台北市大安區忠孝東路四段216巷27弄16號',
    servingsMin: 4,
    servingsMax: 6,
    orderDeadline: '2025-01-20',
    fulfillStart: '2025-01-26',
    fulfillEnd: '2025-01-29',
    canSelectDate: false,
    tags: ['素食', '蔬食', '有機'],
    dishes: [
      '素佛跳牆',
      '養生五穀飯',
      '麻油猴頭菇',
      '紅燒獅子頭（素）',
      '什錦蔬菜羹',
    ],
    status: 'published',
  },
  {
    vendorId: 'v7',
    vendorName: '海霸王',
    title: '海鮮饗宴年菜組',
    description: '新鮮海產直送，鮮味滿滿',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
    priceOriginal: 8800,
    priceDiscount: 7280,
    shippingFee: 0,
    shippingType: 'both',
    storageType: 'frozen',
    region: 'south',
    city: '高雄市',
    address: '高雄市前鎮區中華五路789號',
    servingsMin: 6,
    servingsMax: 8,
    orderDeadline: '2025-01-23',
    fulfillStart: '2025-01-25',
    fulfillEnd: '2025-01-29',
    canSelectDate: true,
    tags: ['海鮮', '台式', '無甲殼類'],
    dishes: [
      '清蒸鱈魚',
      '蒜蓉蒸蝦',
      '三杯中卷',
      '干貝燴白菜',
      '海鮮米粉',
      '鮮魚羹',
    ],
    status: 'published',
  },
  {
    vendorId: 'v8',
    vendorName: '福容大飯店',
    title: '迎春納福禮盒',
    description: '精選經典菜色，品質保證',
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=400&h=300&fit=crop',
    priceDiscount: 5580,
    shippingType: 'delivery',
    storageType: 'frozen',
    region: 'north',
    city: '桃園市',
    address: '桃園市中壢區中園路178號',
    servingsMin: 4,
    servingsMax: 6,
    orderDeadline: '2025-01-19',
    fulfillStart: '2025-01-26',
    fulfillEnd: '2025-01-28',
    canSelectDate: false,
    tags: ['台式', '粵式'],
    dishes: [
      '紅燒蹄膀',
      '蜜汁火腿',
      '清蒸鱸魚',
      '干貝白菜',
    ],
    status: 'published',
  },
  {
    vendorId: 'v9',
    vendorName: '新東南海鮮餐廳',
    title: '海陸全席年菜',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    priceDiscount: 6800,
    shippingType: 'pickup',
    storageType: 'chilled',
    region: 'south',
    city: '台南市',
    address: '台南市中西區民生路一段168號',
    servingsMin: 6,
    servingsMax: 8,
    orderDeadline: '2025-01-24',
    fulfillStart: '2025-01-28',
    fulfillEnd: '2025-01-29',
    canSelectDate: true,
    tags: ['海鮮', '台式'],
    dishes: [],
    status: 'needs_review',
  },
  {
    vendorId: 'v10',
    vendorName: '王品集團',
    title: '尊爵年菜禮盒',
    priceDiscount: 8880,
    shippingType: 'delivery',
    storageType: 'frozen',
    region: 'nationwide',
    servingsMin: 6,
    tags: [],
    dishes: [],
    status: 'draft',
  },
];

export async function seedMockData(addPlanFn: (plan: Omit<Plan, 'id' | 'createdAt' | 'updatedAt'>) => Promise<string>) {
  for (const plan of mockPlans) {
    await addPlanFn(plan);
  }
}
